guardian/transcription-service

.github/workflows/build-whisper-docker.yml, .github/workflows/ci.yaml, package-lock.json, packages/cdk/bin/cdk.ts, packages/cdk/lib/repository.ts, packages/cdk/riff-raff-repository.yaml, whisper_container/Dockerfile
From my testing so far, for some reason whisper seems to load a bit faster when run from a docker container. So far I have tried:
- Checking out whisper.cpp on a machine, compiling then running a transcription using jfk.wav and the medium model - slow load times (over a minute)
- `docker pull` a container generated by this action with jfk.wav and medium model - fast load time (under 10 seconds)
There is probably something we can tweak in the way we are 'installing' whisper.cpp but I think there might be some benefit to using a docker container regardless - as it allows us to have the code that determines what models are available here in our repo rather than buried in [amigo](https://github.com/guardian/amigo).
I am hoping that this work combined with …
=> Add Github Actions Workflow to publish a whisper docker container to github packages

.github/workflows/ci.yaml
This adds an offset to the build number of our main github actions CI build after the changes in https://github.com/guardian/transcription-service/pull/4 caused it to be reset to 0 (I renamed the gha workflow yml file)
This also adds the [workflow_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) trigger so we can manually trigger builds
I've tested this by running a few builds on a different branch -seems to do the job
=> Fix build number following workflow file rename, allow manual build triggers

packages/cdk/riff-raff.yaml
Let's make use of riffraff's auto AMI update functionality to make sure our transcription workers are always using the latest AMI baked by AMIgo.
Tested on CODE
=> Auto update worker AMI with RiffRaff

.github/workflows/ci.yaml
Fixes a naming bug introduced in https://github.com/guardian/transcription-service/pull/4 - riffraff expects the artifact for the worker to be in a directory called transcription-service-worker
I've tested this by deploying it using riffraff, it resolves deployment errors like this one https://riffraff.gutools.co.uk/deployment/view/f0de3b31-faba-4396-bf35-ff0d383cd927
=> Fix riffraff upload step for worker app

packages/cdk/riff-raff.yaml
AMIgo bakes 3 encrypted AMIs for our account so we need to tell riffraff which one to use
=> Tell riffraff which encrypted AMI to use

packages/api/src/index.ts, packages/api/src/services/passport.ts
A fix that was missed in previous PR https://github.com/guardian/transcription-service/pull/7
- checkAuth is added and pattern on using it is to add it to every api endpoint
- the emulate prod locally was looking at the wrong location for static client files
=> fix emulate prod locally and check auth for api endpoints

.husky/pre-commit, package-lock.json, package.json, tsconfig.json
- Adds a [pre-commit hook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) to format staged files with prettier and lint them with eslint
- installs [`husky`](https://typicode.github.io/husky/#/), a tool to configure git hooks
- installs [`lint-staged`](https://github.com/okonet/lint-staged), [recommended by prettier](https://prettier.io/docs/en/precommit.html) for projects that also want to run eslint in a hook and support partially staged files.
This should help us avoid noisy git history due to formatting and linting changes unrelated to the main motivation of a commit. 
Automatic formatting should allow contributors and reviewers to ignore formatting and focus on more substantial code changes.
- try to commit changes that break eslint rules. Fixable changes like incorrect …
=> Format and lint with precommit hook

package-lock.json, packages/cdk/lib/__snapshots__/transcription-service.test.ts.snap, packages/cdk/lib/transcription-service.ts, packages/common/package.json, packages/common/src/config.ts, packages/common/src/s3.ts, packages/common/src/sqs.ts, packages/common/src/types.ts
Paired with @marjisound and @zekehuntergreen 
This PR:
- Adds a new S3 bucket to hold source media for the transcription service
- Adds permissions to the worker to fetch and delete from the bucket
- Updates packages/common/src/types.ts to include all relevant fields we think will be needed to be passed between our different services
This code doesn't actually do anything yet so I think is safe to merge if the build passes. I've deployed to CODE to check that the deploy works
=> Add initial s3 infrastructure, zod types

packages/cdk/target_tracking_scaling_policy/config.json
Fixes scaling policy introduced in #11 
At the moment, when there are 0 worker instances, `e1` evaluates to `NaN`. This means that the scaling policy cloudwatch alarms always have insufficient data and we'll never scale out the ASG.
This fix coalesces the number of instances to .99 (just under our target backlog per instance of 1) to avoid division by 0.
I tried using [`FILL`](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/using-metric-math.html) to convert missing `GroupInServiceInstances` values to 0 but this didn't seem to work. 
`(FILL(m1, 0) + FILL(m2, 0)) / FILL(m3, .99)` evaluated to undefined regardless of number of instances or messages in the queue
=> Fix target-tracking ASG scaling policy

packages/cdk/lib/transcription-service.ts
Adds tags to ASG and role permissions to write to log kinesis stream so logs (including application logs) go to central ELK. 
Tested on [CODE](https://logs.gutools.co.uk/s/investigations/goto/f525deb0-c5e0-11ee-a363-830c35c1ec3b) - logs are there.
=> Setup log shipping to central ELK

packages/worker/deb-build/Dockerfile, whisper_container/Dockerfile
We have 2 containers in this project at the moment - one used for building a .deb package for the worker package, another containing ffmpeg and whisper.cpp.
This PR gets them both to use the same debian bookworm 'slim' image (bookworm is the latest version of debian). This isn't a significant improvement - both ubuntu and bookworm-slim containers are a similar size, but it's good to be consistent - and there may be some security benefits from using a 'minimal' image versus ubuntu.
If we really wanted to optimise our containers we could use alpine linux, but given that we're including giant whisper models in our main container, I'm not sure it's worth the hassle
Some background here https://www.chainguard.dev/unchained/minimal-container-images-towards-a-more-secure-future
The worker build …
=> Use debian bookworm-slim for worker container

.github/workflows/build-whisper-docker.yml, packages/worker/src/index.ts, packages/worker/src/transcribe.ts, whisper_container/Dockerfile
To make testing transcription a bit quicker, this sets us up to use the `tiny` whisper model on CODE. As we are using less powerful workers on CODE we need to use a smaller model so that transcription doesn't take _forever_
As part of this I've also tried to speed up the builds for the docker container by using github actions cache - https://docs.docker.com/build/cache/backends/gha/
Deploy to CODE, run a transcription. Leaving this as a draft pending the main worker transcription PR being merged
=> Use tiny model to transcribe on CODE

package-lock.json, packages/api/package.json, packages/api/src/index.html, packages/api/src/index.ts, packages/api/src/services/googleDrive.ts, packages/backend-common/src/configHelpers.ts, packages/backend-common/src/dynamodb.ts, packages/cdk/lib/transcription-service.ts, packages/client/package.json, packages/client/src/app/about/page.tsx, packages/client/src/app/export/page.tsx, packages/client/src/app/page.tsx, packages/client/src/app/template.tsx, packages/client/src/components/ExportButton.tsx, packages/client/src/components/UploadForm.tsx, packages/client/src/helpers.ts, packages/client/src/services/export.ts, packages/common/src/types.ts, packages/output-handler/src/index.ts
The main aim here is to allow users to export a transcript to a google doc. This involves the following features:
Client:
- A new 'Export' page. This is the first React page that we have that is not just index.html. The way Next.js works is that it creates a separate page.html file for each page. As such I have had to update the production handler for client side pages -previously we always just returned index.html
- A new 'ExportButton' component to handle export, waiting for an export, and linking to the generated google doc
- `export.ts` service on the client which handles authentication with google to get permsissions to write to google drive
- I've refactored `authFetch` to allow the entire request object to be overridden
Server:
- A new /export endpoint to trigger the export and …
=> Support export to google doc

packages/api/src/index.ts, packages/backend-common/src/config.ts, packages/backend-common/src/dynamodb.ts, packages/backend-common/src/index.ts, packages/backend-common/src/s3.ts, packages/backend-common/src/sqs.ts, packages/backend-common/src/utils.ts, packages/cdk/lib/__snapshots__/transcription-service.test.ts.snap, packages/cdk/lib/transcription-service.ts, packages/client/src/components/UploadForm.tsx, packages/common/src/index.ts, packages/common/src/types.ts, packages/common/src/utils.ts, packages/output-handler/src/index.ts, packages/output-handler/test/testMessage.ts, packages/worker/package.json, packages/worker/src/asg.ts, packages/worker/src/index.ts, packages/worker/src/transcribe.ts, packages/worker/src/util.ts
This PR does the following:
- CDK - Creates a bucket for storing the transcripts output (srt, json & text)
- CDK - gives `s3:PutObject` permission on the bucket to the api lambda
- CDK - gives `s3:GetObject` permission on the bucket to the outputHandler lambda
- API - Creates S3 upload signed urls for the transcript output before sending the message to SQS
- API - Adds the signed urls to the SQS message
- Worker - Uploads the transcripts to the relevant S3 bucket using the signed urls
- Worker - Adds the S3 keys of the uploaded output files to the SNS message
- Output Handler - Downloads the transcripts from the output bucket using the keys provided by the SQS message
- Output Handler - Reads the transcripts files and adds their text to the object that goes to dynamo db
Tested in code by …
=> Use signed urls for transcription output

.gitignore, package-lock.json, packages/backend-common/package.json, packages/backend-common/src/cloudwatch.ts, packages/backend-common/src/metrics.ts, packages/cdk/lib/__snapshots__/transcription-service.test.ts.snap, packages/cdk/lib/transcription-service.ts, packages/output-handler/src/index.ts, packages/worker/src/index.ts
This change adds the capability to post metrics to cloudwatch from our transcription service.
Initially, I have created one new metric called `Failure` to record failures during the transcription process. At the moment this metric will be updated in the following situations:
- If the worker fails to parse an incoming SQS message
- If the FFMPEG conversion or whisper transcription fails 
- If the output-handler fails to either write to dynamo or send a notification email.
I wasn't sure whether to make the different failure scenarios different metrics or not (e.g. counting transcription failures in a different metric to 'notification failed' failures). I decided to put everything together with the idea that all we want to know is that something failed - we should then be able to go and look …
=> Add failure metric to worker and output-handler services

packages/cdk/lib/transcription-service.ts
Adds `devx-backup-enabled` tag to enable nightly backups
Deployed to CODE, tag is present.
=> Adding devX managed nightly backups

package-lock.json, packages/api/src/index.ts, packages/backend-common/package.json, packages/backend-common/src/s3.ts, packages/backend-common/src/sqs.ts, packages/cdk/lib/transcription-service.ts, packages/client/src/components/UploadForm.tsx, packages/common/src/types.ts, packages/worker/.gitignore, packages/worker/src/index.ts
- updates the `transcribe-file` api endpoint (renamed from `send-message`) so that it 
- takes an  `s3Key` parameter 
- creates a presigned url to download the file with the given key in the uploads bucket
- adds a message to the task queue (with non-test data) including this url so that the worker can use it to get the file
- change to client so that when the user submits the form, after the file is uploaded to s3, `transcribe-file` is called.
- change to worker so that it uses this presigned url rather than having access to the entire bucket. This change is important because it will allow third parties to integrate with the transcription service without our having to change any of the worker permissions. 
- can be tested locally by starting api, client, worker
- testing in CODE
-   [ ] …
=> Add message to task queue when file is uploaded

packages/cdk/lib/__snapshots__/transcription-service.test.ts.snap, packages/cdk/lib/repository.ts, packages/cdk/lib/transcription-service.ts
Prior to this PR we hadn't configured a security group for our transcription worker autoscaling group. As a result AWS applied the fallback default security group, which allows all outbound traffic.
For security reasons we'd like to block outbound traffic. Key considerations are:
- Reassurance that transcript/audio data is not getting sent to some third party. Locking down egress traffic ensures this
- If a users uploads some malware rather than some audio to transcribe, we want to limit the potential impact
This PR locks down egress traffic from the worker instances by applying a security group. However, in order to operate the worker does need access to some AWS services:
- S3 - to download the worker deb package and transcript files
- SQS - to fetch new transcript jobs
- Autoscaling - …
=> Block egress traffic from workers (except for AWS services)

packages/cdk/lib/transcription-service.ts
The changes in https://github.com/guardian/transcription-service/pull/34 broke our cloudformation deploys because cloudformation stack export names must be unique - they can't be the same for CODE and PROD. This change adds the stage to ensure this.
=> Include Stage in worker Arn output parameter

.github/workflows/ci.yaml
Follow [directions in actions-riff-raff](https://github.com/guardian/actions-riff-raff?tab=readme-ov-file#migrating-from-v3-to-v4) to upgrade from version 3 to 4.
v4 avoids the need for configure-aws-credentials which stores aws credentials in an environment variables, allowing other, possibly malicious, actions to access them.
=> Upgrade actions-riff-raff to v4

packages/cdk/lib/transcription-service.ts
temporarily remove the worker security group - we think this is causing workers not to be able to fetch media files from s3
=> hotfix: remove worker security group

packages/cdk/lib/transcription-service.ts
I'm currently in the process of updating the default security groups in our AWS account so that by default they block all traffic. We are currently facing some problems with the VPC endpoints that allow transcription workers to interact with AWS services - whilst we debug that we want to allow all outbound traffic. 
With that in mind this PR makes sure a SG is explicitly applied to the worker launch template so that instances don't fall back to using the default security group, which will soon block outbound traffic.
A variation on https://github.com/guardian/transcription-service/pull/42
=> Set security group on worker instances but allow all outbound.

packages/worker/src/asg.ts, packages/worker/src/index.ts
- changes transcriptions workers so that they poll the task queue every 30 seconds, rather than only polling once, when they're started up.
- this should help to stop workers from getting into a state where they are doing no work but preventing other workers from taking their place
=> Worker polls for transcription tasks every 30 seconds

packages/cdk/lib/transcription-service.ts, packages/worker/src/index.ts
- cdk for a dead letter queue where transcription task messages are moved after 3 failed attempts
- also includes a small change to workers to log a message and exit early when sqs message receipt handle is missing
=> Create dead letter queue for transcription tasks

packages/api/src/index.ts, packages/backend-common/src/config.ts, packages/backend-common/src/sqs.ts, packages/cdk/lib/transcription-service.ts, packages/worker/src/index.ts, packages/worker/src/transcribe.ts, scripts/setup.sh
- updates CDK to allow worker instances to write sqs messages to the dead letter task queue
- when workers fail when processing a file that can't be converted to a wav, move the sqs message to the dead letter queue
=> Move task to dead letter queue when conversion to wav fails

packages/backend-common/src/sqs.ts
We are using a FIFO SQS queue so need to set a unique message group ID for each transcription - otherwise we can't start processing the next transcription until the one in front of it in the queue is there
=> Set unique message group id

packages/backend-common/src/sqs.ts
Reverts guardian/transcription-service#50 - I messed up the rebase and `id` is not available at this point! New pr coming soon
=> Revert "Set unique message group id"

packages/backend-common/src/sqs.ts, packages/worker/src/index.ts
Another go at https://github.com/guardian/transcription-service/pull/50 - we need to set a unique MessageGroupId for each transcription job going to SQS - otherwise we can't process transcription jobs in parallel.
I decided to use the transcript ID for the MessageGroupId, seems as good as anything
=> Use the transcription id to provide a uniqe MessageGroupId

package-lock.json, packages/api/src/controllers/GoogleAuth.ts, packages/api/src/index.ts, packages/api/src/services/googleDrive.ts, packages/backend-common/package.json, packages/backend-common/src/cloudwatch.ts, packages/backend-common/src/config.ts, packages/backend-common/src/configHelpers.ts, packages/backend-common/src/dynamodb.ts, packages/backend-common/src/index.ts, packages/backend-common/src/logging.ts, packages/backend-common/src/s3.ts, packages/backend-common/src/sqs.ts, packages/client/src/components/UploadForm.tsx, packages/common/src/utils.ts, packages/output-handler/src/index.ts, packages/output-handler/src/ses.ts, packages/worker-capacity-manager/src/asg.ts, packages/worker-capacity-manager/src/index.ts, packages/worker-capacity-manager/src/sqs.ts, packages/worker/src/asg.ts, packages/worker/src/index.ts, packages/worker/src/sns.ts, packages/worker/src/transcribe.ts, packages/worker/src/util.ts
This PR adds `winston` logging library (only for serverside logging) in order to send structured data for logging and also improve the logging behaviour. 
The following improvements were done: 
- adds userEmail, fileName, message id to the API logging where the message is successfully pushed to SQS
- adds userEmail, fileName, file duration and message id to the WORKER logging where message is successfully sent to SNS
- adds userEmail, fileName, message id to the output handler logging where email is successfully sent
- adds message id and user email to all worker loggings (after sqs message is parsed up to when the processing is finished for that message)
- adds @timestamp to all messages - if this field doesn't exist in the log message, the DevEx tool that ships logs to ELK automatically …
=> Improve logging using winston

packages/api/src/index.ts
The api logs are full of this deprecation notice from serverless express
```
message | [DEPRECATION NOTICE] You're using the deprecated `serverlessExpress({...}).handler({...})` method. This will be removed in a future version of @codegenie/serverless-express. Instead, simply return `serverlessExpress({...})` as your handler.
```
This PR makes the recommended change so that logs are less noisy
=> Fix serverless express deprecation notice

packages/client/src/app/template.tsx
I noticed we flash a 'login required' message on most pages even when the user is logged in. This change adds a loading spinner when we're reading the value from local storage, and pulls the call to createBrowserHistory to the top of the component - which appears to speed things up a bit though would be good to check with @marjisound if you think this will work.
Before:
https://github.com/guardian/transcription-service/assets/3606555/5e930c3f-3319-47b8-b354-6a86d6731879
After:
https://github.com/guardian/transcription-service/assets/3606555/d939b2a7-92d7-40fa-b844-8e57c2a91b32
=> Tidy up UI - don't flash 'login required' message

packages/cdk/lib/__snapshots__/transcription-service.test.ts.snap, packages/cdk/lib/transcription-service.ts, packages/cdk/riff-raff.yaml
To make it easier to identify in the logs, let's give transcription-service-api a more precise tag.
I created a change set just to check this wasn't going to explode anything, looks ok:
=> Set app tag of api to transcription-service-api

packages/backend-common/src/logging.ts, packages/worker/src/index.ts, packages/worker/src/transcribe.ts
This pr uses some regular expressions to extract useful information out of the whisper.cpp output. Currently, we extract language code, total time and load time (time taken to load the model).
I've tested this on CODE - here's an example log line https://logs.gutools.co.uk/s/investigations/app/discover#/doc/3501e690-a763-11eb-882c-5b432fbcaa69/logstash-investigations-2024.02.29?id=Acc69Y0BLE-XvQ1FY3Mn
=> Extract timing and language data from transcript output

packages/cdk/lib/__snapshots__/transcription-service.test.ts.snap, packages/cdk/lib/transcription-service.ts, packages/worker/src/index.ts
This adds 3 cloudwatch alarms to the PROD transcription stack:
- dead letter alarm - if a message goes into the dead letter queue it suggests a user upload has failed to process, so we alarm on that condition
- transcription failure alarm - we already have a metric added in https://github.com/guardian/transcription-service/pull/32 to track failures. This adds an alarm to that metric
- Long running instances alarm - this will alarm if we have more than 0 instances running for a period of 5 hours (this might need some tweaking to get it right)
Depends on https://github.com/guardian/investigations-platform/pull/480
I've tested these alarms by:
- manually publishing a message to the dead letter queue
- killing docker part way through a transcription
- running some transcriptions for a long …
=> Add alarms for failures and cost warnings

packages/worker/src/index.ts
Tiny change - this would allow us to have a table visualisation in our ELK cluster of e.g. average file length, max file length etc
=> Make file duration a number in logs

packages/backend-common/src/sqs.ts, packages/cdk/lib/transcription-service.ts, packages/cdk/package.json, packages/common/src/constants.ts, packages/common/src/index.ts, packages/common/src/types.ts, packages/output-handler/src/index.ts, packages/output-handler/src/ses.ts, packages/output-handler/test/testMessage.ts, packages/worker/src/index.ts
- updates the types of the messages the worker pushes to SNS so that they can include failure messages as well as success messages
- workers post a failure message to SNS in two situations 
- when ffmpeg fails to convert a file to a wav
- when an exception is thrown after the SQS task message is parsed on the third retry
- the output handler processes worker failures by sending an email to the user
- tested in CODE
=> Email notification on worker failure

packages/worker/src/index.ts
In https://github.com/guardian/transcription-service/pull/59 I converted fileDuration from being a string to a number. Unfortunately once data has been added to an elasticsearch mapping you can't change the format without doing a reindex. Having a mix of numberic and text data prevents from using the field in any formulas/visualisations, and shows an error:
With that in mind, I'm just making a new field to store this data, with a slightly improved name.
=> Rename file duration field to mediaDurationSeconds

packages/cdk/lib/__snapshots__/transcription-service.test.ts.snap, packages/cdk/lib/transcription-service.ts, packages/worker/src/index.ts, packages/worker/src/spot-termination.ts
In order to reduce the costs for our transcription service, let's use spot instances for the transcription workers.
A lot of the infrastructure for using spot instances was added in https://github.com/guardian/transcription-service/pull/4 - that PR has quite a bit of detail. What this change does is actually 'switch on' spot instances by setting `onDemandPercentageAboveBaseCapacity` to 0. With that change, all instances will be launched as spot instances. This means
- instances may take a little longer to start up
- instances may be terminated with 2 minutes notice - see [spot interruption notice](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-instance-termination-notices.html)
Regarding the startup time, we should monitor this (will be easier once we have more structured logs …
=> Use spot instances

packages/api/src/index.ts
If a transcription takes more than 2 hours and gets killed halfway through by e.g. spot instance rotation then it will need to be re-downloaded.
With that in mind, let's set a longer expiry for the s3 download url
=> Bump transcription file signed download url timeout to 7 days

packages/worker/src/index.ts
Raises SQS message visibility timeout from a constant `file duration + 5 minutes` to `file duration * 2 + 10 minutes`
At the moment we've got a bug where we're setting SQS message visibility timeout to a value that is too low after having converted the corresponding file to wav and determining its duration. By the time transcription is finished, the visibility timeout has expired. We email the user with a success notification but fail to delete the message off of the queue because the message's receipt handle (with duration equal to message visibility) has expired. The worker then reattempts transcription twice with the same outcome, before the message is sent to the dead letter queue.
Must be tested in prod since CODE use whisper's tiny model which is faster than prod's medium model, and …
=> Fix: raise worker visibility timeout

packages/cdk/lib/__snapshots__/transcription-service.test.ts.snap, packages/cdk/lib/transcription-service.ts
This re-implements changes initially introduced in https://github.com/guardian/transcription-service/pull/34, after they were removed for debugging in https://github.com/guardian/transcription-service/pull/42 and https://github.com/guardian/transcription-service/pull/44
With this change, worker instances will only have egress access to a limited number of AWS services 
I deployed this change to CODE and verified
- Transcription works (this should test communication with s3, sqs, sns, parameter store)
- logs work (tests kinesis)
=> Block outbound traffic from worker instances

packages/cdk/lib/transcription-service.ts
We no longer need to receive an email every time a transcription is completed as we can use the [usage dashboard](https://metrics.gutools.co.uk/d/BjGFOolnk/investigations-tools-usage?orgId=1&from=1709683200000&to=1709942399000) to analyse usage of the tool.
=> Remove notifications to digital.investigations

packages/backend-common/src/sqs.ts
This fixes small bug where we were setting the expiry time in minutes when the unit is actually seconds. Currently transcriptions will fail to upload after 168 minutes instead of 7 days
I haven't tested this, but I've checked the docs and the unit is definitely seconds.
=> Set s3 expiry time in minutes not seconds

packages/client/src/components/UploadForm.tsx
A user noted that the message saying 'The transcription process is typically shorter than the length of the media file' led them to think the service had failed when they tried an extremely short recording. So I thought it might help to suggest that there is always a minimum turnaround time of a few minutes, even if the transcription worker itself is typically faster than the recording's duration.
Edit made in a text editor so may need prettifying
=> Add a note pointing out that the email will always take at least a few minutes

packages/backend-common/src/sqs.ts, packages/client/src/app/page.tsx, packages/client/src/components/UploadForm.tsx, packages/common/src/languages.ts, packages/common/src/types.ts, packages/worker/src/transcribe.ts
- changes transcription form so that there is no default language chosen, and the user must either select a language or 'Auto-detect language'.
- fixes the form on mobile by changing the language picker from a flowbite-react `Dropdown` element to a react `Select` element. The former didn't work on some mobile devices. When it was selected, the dropdown opened upward (regardless of `placement` property) and couldn't be navigated by swiping or scrolling.
- improves handling of form state by moving from a query selector to get files on form submission, to keeping track of that state with a `useState` hook
auto-detect language is the default, language picker doesn't work
https://github.com/guardian/transcription-service/assets/17057932/ec16286c-5e80-40b0-9744-260ffc4aaf8e
no default language, …
=> Enforce selection of media file language

packages/client/src/components/ExportButton.tsx
Updates messages while the google auth window should be open and when authentication fails. We've had two users email us about auth errors that were caused by the browser blocking the pop-up.
https://github.com/guardian/transcription-service/assets/17057932/73fa09ed-2fbe-40e6-b26a-406c9e0359e7
=> Update export page wording to encourage users to allow pop-ups

packages/api/src/index.ts, packages/client/src/app/layout.tsx, packages/client/src/components/ExportButton.tsx, packages/client/src/services/export.ts, packages/common/src/types.ts
This PR adds options on the transcripts format when user is exporting the transcripts to a google document. The options are text and srt. It also adds validation so user can not submit the export unless they choose the format. 
The api is also updated to use the `transcriptFormat` value from the query parameters in order to provide the relevant text format.
Tested locally and in CODE
=> Add option to choose the transcript format

packages/client/src/app/layout.tsx
Adds a footer component to the page with a link to our [user-facing docs](https://docs.google.com/document/d/1e224Fe5tJJNeLBNvYLVJ4FWd_O-1nwrJcqKyEXI03lA/edit#heading=h.faz67d5pl5mg).
=> Create footer with link to docs

packages/output-handler/src/index.ts
Co-authored-by: Marjan Kalanaki <marjan.kalanaki@guardian.co.uk>
Adds message id to the failure notification email we send to users when their transcription fails.
Debugging a recent issue based on a failure email forwarded to the team involved digging through logs and s3 in order to find job id based on original file name. This change should make debugging easier by surfacing this information.
=> Add message id to failure notification

packages/backend-common/src/dynamodb.ts
Following from https://github.com/guardian/transcription-service/pull/78 - the new completedAt field needs to be optional to allow for any transcriptions completed in the past 7 days. After 7 days we can revert this PR.
=> Make completedAt optional

.github/workflows/ci.yaml, package-lock.json, packages/cdk/lib/transcription-service.ts, packages/cdk/package.json
This PR 
- removes `@guardian/private-infrastructure-config` dependancy. We were using this dependancy to retrieve the account id, now we are retrieving the account id from `this.account` instead. 
- removes the github action `guardian/actions-read-private-repos`. This action was only needed to access the `@guardian/private-infrastructure-config` dependancy
Tested in code
=> remove the need for actions-read-private-repos action

packages/cdk/lib/transcription-service.ts
Sets worker autoscaling group on-demand percentage to 10%
On-demand percentage of the worker ASG is currently 0% so when there are no spot instances available in our AWS region, the ASG is unable to scale with the transcription job queue. This happened over the weekend resulting in a backlog of 14 jobs and a few failed transcriptions. We should keep on-demand percentage at > 0% until we find a way to use 100% spot instances, unless there are none available, in which case we fall back to on-demand instances.
Deployed to prod
=> Hotfix: set worker ASG `onDemandPercentageAboveBaseCapacity` to 10

packages/cdk/lib/__snapshots__/transcription-service.test.ts.snap, packages/cdk/lib/transcription-service.ts
When “transcription-service-worker-instances-PROD“ is in alarm, it is usually a false positive. The alarm is triggered when the capacity of the ASG is at least 1 for a period of 5 hours. Since the service is used so heavily, this is not an uncommon occurrence during business hours.
Now that the transcription service is stable, we're raising the threshold from at “least one instance running for 5 hours” to  “at least one instance running for 12 hours”?
We also considered a change to the worker-capacity-manager to describe all instances of the ASG, then find if any of them was older than x hours. This would be a more useful, descriptive alarm, but we've decided to forego this idea for the moment   in favor of other priorities.
=> Raise long-running worker alarm threshold to 12 hours

packages/client/src/app/layout.tsx
This PR resolves a bug where on certain phone screens you can't click the submit button because the 'about this tool' footer thing gets in the way. As the footer is absolutely positioned it will go on top of the submit button. We resolve this by adding some padding 🥳 
Use a 'short and wide' phone layout to reproduce the bug
=> Add padding under main div to ensure space for footer

packages/backend-common/src/config.ts, packages/backend-common/src/sqs.ts, packages/cdk/lib/transcription-service.ts, packages/common/src/types.ts, packages/worker/src/index.ts, packages/worker/src/transcribe.ts, scripts/delete-local-queues.sh, scripts/purge-local-queue.sh, scripts/purge-local-queues.sh, scripts/setup.sh
This PR is enabling transcription service to process messages coming from third parties service (in particular 'Giant'). 
- The config model for `destinationQueueUrls` is updated so that we can now dynamically get the destination value based on if the message is coming from transcription or giant. 
- the worker message output is now published to the relevant service based on the value of `transcriptDestinationService` in the input message
- Added a local dead letter queue for the local task input queue to make it consistent with our code/prod environments
- Added a giant output queue and giant output dead letter queue. In code/prod these queues belong to giant, but in local setup, because adding 2 localstack would have add complication, we decided to have them created as part of the …
=> enabling transcription integration for giant

packages/client/src/app/layout.tsx, packages/client/src/app/page.tsx, packages/client/src/components/UploadForm.tsx, packages/output-handler/src/index.ts
I've just refreshed the wording in the upload form and the emails sent to users, now that it's no longer a new tool. 
Check that I haven't caused any problems with prettier etc
=> Minor changes to user-facing text

packages/client/src/app/layout.tsx
Given expected increase in the tool usage and relative maturity, let's drop the beta tag maybe?
=> Remove beta tag

package-lock.json, packages/cdk/lib/transcription-service.ts, packages/cdk/package.json, packages/media-download/src/index.ts, packages/media-download/src/yt-dlp.ts
Similar to https://github.com/guardian/lurch/pull/751, this PR disables write access to the root file system for ecs containers used in this project (just the media download service at the moment). This is achieved by bumping the version of GuCDK that the project uses to pull in https://github.com/guardian/cdk/pull/2545
With this in place, we then need to make sure that all file write operations happen inside a separate mounted volume - in this case mounted at /media-download
Tested on CODE
=>  Bump CDK to support having readonlyRootFilesystem set to true #751 

packages/client/src/components/UploadForm.tsx, packages/client/src/types.ts
It would be helpful to perform some client side validation on urls being added to the upload form so that we can, e.g. prevent people submitting invalid urls, or urls to youtube search results (as yt-dlp will then try download everything on the page). 
This PR introduces this, by breaking up the existing 'textarea' into individual input elements, as suggested by @zekehuntergreen ages ago. 
Before:
After:
You can run just the API and the client locally to test this - though hopefully screenshots make it fairly clear what's going on. I've not tested on CODE yet as I'm waiting for https://github.com/guardian/transcription-service/pull/115 to go out.
=> Improve url form validation

packages/backend-common/src/sqs.ts
There's a bug in the transcription tool at the moment where both the transcription and the translation end up with the same id, resulting in whichever one finishes last overwriting the other! This fixes that.
=> Use different ID, output urls for translation and transcript

packages/cdk/lib/repository.ts
We currently have a lifecycle rule for our ECR repositories that deletes all but the most recent 5 containers. This is causing problems on PROD, as if a development branch has more than 5 builds then the container tagged with `main` will end up being deleted.
This PR protects containers tagged with `main` from the lifecycle rule.
I've also bumped the number of containers from 5 to 10, 5 seemed a bit small because if you have 2 devs working on 2 branches then they could very quickly end up losing containers needed to test stuff.
Deploy this, kick off a few builds, verify that `main` container isn't deleted
=> Stop auto deleting containers tagged with 'main

packages/cdk/lib/transcription-service.ts
When I tried to deploy the whisperx stuff to PROD I got the cloudformation error "The specified instance type g6.xlarge is not valid"
I think this might just be because we need to enable it for our account (this is sometimes necessary for rarer, expensive instance types) because g6.xlarge definitely is a realy instance type, but for now let's just remove it
This change is already live on PROD
=> Remove g6.xlarge instance type

packages/cdk/lib/__snapshots__/transcription-service.test.ts.snap, packages/cdk/lib/transcription-service.ts
I think I set the maxSpotPrice too high in https://github.com/guardian/transcription-service/pull/123 - I set it to the 'on demand' price of a g4dn.2xlarge, when whisperx seems to run fine on a g4dn.xlarge. With that in mind, I've dropped the max spot price.
Price details here https://instances.vantage.sh/?filter=g4dn.xlarge|g4dn.2xlarge&compare_on=true&selected=g4dn.xlarge,g4dn.2xlarge
Deploy, check for cost savings...
=> Drop max spot price for gpu instances

packages/api/src/export.ts, packages/backend-common/src/dynamodb.ts, packages/backend-common/src/sqs.ts, packages/client/src/components/UploadForm.tsx, packages/common/src/languages.ts, packages/common/src/types.ts, packages/output-handler/src/index.ts, packages/worker/src/index.ts, packages/worker/src/transcribe.ts
I'm currently experimenting with https://github.com/m-bain/whisperX. WhisperX appears to [support fewer languages](https://github.com/m-bain/whisperX?tab=readme-ov-file#other-languages) than whisper.cpp. To understand the impact of moving to whisperX this PR sets the transcription service to record the language code of the transcription in the dynamo database.
I made the new field optional in the zod type to avoid breaking existing transcriptions. In a few weeks we could make it compulsory.
Tested on CODE
=> Store language code in database

packages/backend-common/src/s3.ts, packages/common/src/types.ts, packages/output-handler/src/index.ts
Currently, when you get an output email from the transcription service and click the link to download source media, you get a file called UUID, which isn't very user friendly. This PR sets the filename to the original filename using the 'Content-Disposition' header https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition
Tested on CODE
=> Use original file name when downloading source media

packages/cdk/riff-raff.yaml
I spotted an issue recently on CODE where...
- A [deploy failed](https://riffraff.gutools.co.uk/deployment/view/80ee3a10-db50-41e5-b829-0f8c3183b5aa) due to issues with the cloudformation, but the  transcription-service-worker [uploadStaticFiles] step completed
- Ran a transcription, which failed, because the worker fetched a version of the transcription worker application that was incompatible with the infrastructure it was running on (as the cloudformation step failed)
This change will prevent that from happening, by ensuring that if the cloudformation deploy fails, we don't replace the whisper worker code in s3.
Tested on CODE by running a deploy and verifying that the worker deploy waited for the cfn deploy to finish before starting
=> Ensure cloudformation deploy succeeds before deploying worker artifact

packages/cdk/lib/__snapshots__/transcription-service.test.ts.snap, packages/cdk/lib/transcription-service.ts
I've seen occasionaly failures in the media download service because yt-dlp yt-dlp needs to be able to write to the /tmp directory. In https://github.com/guardian/transcription-service/pull/114 I made the media export filesystem read only, allowing writes to a /media-download mounted volume. This PR adds an extra volume to support writing to /tmp.
I've tested this on CODE. As it doesn't happen every time it's hard to test properly but I think it's a fairly harmless change.
=> Add /tmp volume to media download task container

packages/client/src/components/UploadForm.tsx, packages/client/src/helpers.ts
At the moment, if someone adds a url missing a protocol then it fails validation. 
Tested locally, CODE is blocked on the whisperx work
=> If media urls missing http/https protocol then add https protocol.

packages/cdk/lib/transcription-service.ts, packages/common/src/types.ts, packages/media-download/src/index.ts, packages/output-handler/src/index.ts
I spotted that the media download serivice doesn't actually currently have permission to write to the transcription output queue, so if a media download fails it can't tell the user.
This fixes that, and adds a step to the output handler to send an email to the user explaining what might have happened. It looks like this:
Tested on CODE
=> Handle media download failures 

packages/api/src/services/googleDrive.ts
I thought that the transcription service was broken for cyrillic, but it was actually broken for all files with an apostrophe in the filename. This resolves that by escaping apostrophes in the call to the google drive API
I've tested this locally, think it's good to go
=> Support transcripts with apostrophes in the filename

packages/media-download/src/yt-dlp.ts
I found an issue where the filename of the file downloaded by yt-dlp isn't consistent - for videos from some services it included the file extension whereas for others (in this case bluesky) it didn't, which resulted in the upload to s3 step failing as it had the wrong filename. This PR fixes that by explicitly including the file extension in the downloaded filename using an [output template](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#output-template).
Tested on CODE - it works
=> Set an output template for media download filename

ffmpeg-lambda-layer/README.md, ffmpeg-lambda-layer/publish-ffmpeg-layer.sh, packages/api/src/index.ts, packages/backend-common/src/ffmpeg.ts, packages/backend-common/src/sqs.ts, packages/cdk/README.md, packages/cdk/bin/cdk.ts, packages/cdk/lib/__snapshots__/transcription-service.test.ts.snap, packages/cdk/lib/transcription-service.ts, packages/cdk/lib/universal-infra.ts, packages/common/src/types.ts, packages/media-download/src/index.ts, packages/media-download/src/yt-dlp.ts, packages/output-handler/src/index.ts, packages/worker/src/index.ts, scripts/publish-ffmpeg-layer.sh
Currently we have two available 'engines' for transcription:
- whisperx - supports diarization, is very fast once it gets started, better output formatting, very slow startup (~10mins)
- whisper.cpp - fast(er) startup, less pretty output formatting, no diarization
It seems a shame to wait to spin up whisperx for a file that is only a few minutes long. This PR gets the API to make a decision on which engine to use based on the duration of the file - any files under 10 minutes long where the user hasn't requested diarization will be sent to whisper.cpp, everything else goes to whisperX
To get ffprobe running on lambda I had to create a lambda layer - this is basically just a zip file that gets added to the disk of the lambda vm. 
Tested on CODE
=> Calculate duration of input files in order to decide which engine to use

packages/cdk/lib/transcription-service.ts, packages/media-download/src/index.ts, packages/media-download/src/yt-dlp.ts, scripts/trigger-media-download-service.sh
We keep having problems with different info.json formats coming from different media websites. This change modifies the transcription service so that instead of relying on the 'filename' field in the info.json file, it uses --print-to-file with `after_move:filepath` to get an accurate filename. I learned about this in the [output section of the docs](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#output-template), --print-to-file is documented [here](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#verbosity-and-simulation-options)
I've tested this on CODE with various links, seems to work
=> Media download - stop inferring filename from info.json, use --print template instead

packages/backend-common/src/s3.ts, packages/media-download/src/index.ts
The filename limit on macos/windows is 255/257 chars. We were already truncating to 255 chars, but that resulted in the file extension being lost for long filenames. For url transcripts, the media download worker was only providiing the video title to the  worker/output handler, which meant that the output handler had no chance of generating a download link with the correct extension. This resolved that, by providing  the full title/extension from the media download service to the worker.
A downside of this is that the emails now all say "your download for blah.mp4" instead of "your download for blah" - but to do it properly I'd need to pass through the file extension/name as separate fields all the way through to the output handler, this seems a pragmatic approach for now and brings the …
=> Make sure file extension doesn't get truncated for s3 downloads

packages/api/src/index.ts, packages/backend-common/src/logging.ts, packages/backend-common/src/process.ts
- changes server-side log levels from lower to uppercase to conform to all other services' log levels
- `runSpawnCommand` logs stderr at level `info`. ffmpeg directs all text output to stderr, even when its successful, so creating error logs for this output is misleading
=> Improve worker logs

packages/worker-capacity-manager/src/index.ts
At the moment we're failing to update worker ASG capacity whenever the number of messages in the queue is higher than the ASG max capacity, leading to a backlog of transcription jobs.
Set desired capacity to the min of prod's max capacity and the number of messages in the queue.
=> Hotfix worker capacity manager

package-lock.json, packages/client/package.json
Fix for [CVE-2025-29927](https://github.com/advisories/GHSA-f82v-jwr5-mffw), an authorisation bypass vulnerability which affects all versions of 14.x before 14.2.25. 
More details here https://vercel.com/blog/postmortem-on-next-js-middleware-bypass
Tested on CODE
=> Upgrading next.js to fix CVE-2025-29927

packages/cdk/riff-raff.yaml
Back here https://github.com/guardian/transcription-service/pull/123 when we added the new GPU instance autoscaling group, I neglected to update the riffraff configuration so that it would update the AMI for the new autoscaling group upon deployment.
Today this resulted in an incident where AMIgo deleted the AMI we were using as it was very old, and we were unable to launch workers.
I don't think AMIgo should have deleted the AMI as it was clearly still in use in our launch template - this should have been resolved in https://github.com/guardian/amigo/pull/1507
However, we should be updating our AMIs anyway, so I think this is a good improvement even if we also fix the problem in AMIgo.
See here https://riffraff.gutools.co.uk/docs/magenta-lib/types#cloudformation for the relevant riffraff …
=> Update all transcription service AMIs during deployment

packages/client/src/components/UploadForm.tsx
The media download service currently isn't working. It may take some time to work out a solution, so this PR disables url transcription in the UI with a big red error message to reduce user frustration
It looks like this:
Tested locally, I think this needs to go out sooner rather than later
=> Add warning text explaining that url transcription is out of service

packages/media-download/src/yt-dlp.ts
We had a user complaint about the webm files the transcription tool sometimes outputs. This change sets yt-dlp to prefer the mp4 format rather than webm, following guidance here https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#format-selection-examples
See [here](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#sorting-formats) for details of what the '-S ext' option actually does
I've tested this on CODE and verified that the output video changes from being a webm to a mp4. Only one test case though so it might not work all the time
=> Prefer mp4 format for media download service

package-lock.json, packages/api/src/export.ts, packages/api/src/index.ts, packages/backend-common/package.json, packages/backend-common/src/s3.ts, packages/backend-common/src/sqs.ts, packages/client/src/components/UploadForm.tsx, packages/common/src/constants.ts, packages/common/src/types.ts, packages/common/src/utils.ts, packages/output-handler/src/index.ts, packages/worker/src/index.ts, packages/worker/src/transcribe.ts, packages/worker/src/util.ts
This PR aims to make it easier to add new output formats to the transcription service, as well as generally simplifying how files are handled in the service.
Right now, when a transcript is requested the API generates 3 presigned urls for the srt, text and json output formats we request from whisper. These are passed via SQS and used by the worker to upload the output files. The output handler then downloads the files from these locations.
Handling 3 different urls for every transcript adds a bit of complexity.
In this PR I'm adding the concept of 'combinedOutput' which is a single json file containing the transcription output in every format. This would mean that the API (or Giant) just need to provide a single presigned url to the transcription service, the worker only needs to upload …
=> Combine all transcription output text into a single JSON file

packages/api/src/export.ts, packages/api/src/index.ts, packages/client/src/components/ExportForm.tsx, packages/common/src/constants.ts, packages/common/src/types.ts, packages/output-handler/test/testMessage.ts
Following from https://github.com/guardian/transcription-service/pull/167, this updates the direct download functionality added in https://github.com/guardian/transcription-service/pull/156 to use the new combined output file. With this in place, along with this giant update https://github.com/guardian/giant/pull/279 we can deprecate the old way of handling transcription output
Run a transcript on CODE (https://transcribe.code.dev-gutools.co.uk/) and check that these links work on the export page:
=> Use combined output file for downloads

packages/cdk/lib/alarms.ts, packages/cdk/lib/transcription-service.ts
If, for some reason (e.g. unavailable spot capacity, invalid AMI) the transcription worker autoscaling group can't start any instances, then messages will just stay in the task queue indefinitely. This would be helpful to know about so we can login and give the workers a kick. 
As part of this I pulled the alarms out into a separate file which makes this harder to review - the actual new alarms are in here https://github.com/guardian/transcription-service/pull/177/commits/fe72aedb4428514cda9d7dd5f4c7c1b9dc881c89
**Alarm threshold**
Initially I set this to just 1 minute, thinking that the longest a message should be in the queue is the amount of time that an instance takes to start up - but that's wrong - messages stay in the queue until the transcription has finished (they are just not …
=> Alarm when a message has been in the task queue for more than a minute
